
--FUNCIONES DE AGREGACION

--COUNT : CUENTA EL NUMERO DE FILAS O VALORES NO NULOS EN UNA COLUMNA

SELECT COUNT(*) AS total_users FROM users;

--SUM: CALCULA LA SUMA DE LOS VALORES EN UNA COLUMNA

SELECT SUM(quantity) AS total_quantity FROM sales

--AVG: CALCULA EL PROMEDIO DE LOS VALORES DE UNA COLUMNA

SELECT AVG(price) AS average_price FROM products

-- MIN: DEVUULEVE EL VALOR MINIMO DE UNA COLUMNA

SELECT MIN(price) AS min_price FROM products;

--MAX: DEVUELVE EL VALOR MAXIMO DE UNA COLUMNA

SELECT MAX(price) AS max_price FROM products;



-- FUNCIONES DE CADENA

--CONCAT: CONCATENA DOS O MAS CADENAS DE TEXTO.

SELECT CONCAT(first_name, ' ', last_name) AS full_name FROM customers;

--SUBSTRING: EXTRAER UNA PARTE DE UNA CADENA DE TEXTO.
SELECT SUBSTRING(title,1,10) AS shotened_title FROM books;

-- LENGTH : DEVUELVE LA LONGITUD DE LA CADENA DE TEXTO.
SELECT LENGTH(description) AS description_length FROM products;

-- UPPER: CONVIERTE UNA CADENA DE TEXTO A MAYUSCULAS
SELECT UPPER(name) AS uppercase_name FROM users;

-- LOWER: CONVIERTE UNA CADENA DE TEXTO A MINUSCULAS
SELECT LOWER(email) AS lowercase_name FROM users;


--FUNCIONES DE FECHA Y HORA

--NOW: DEVUELVE LA FECHA Y HORA ACTUAL.
SELECT NOW() AS current_datetime;

--DATE_FORMAT: FORMATEA UNA FECHA EN UN FORMATO ESPECIFICO
SELECT DATE_FORMAT(birth_date, '%d-%m-%Y') AS formatted_date FROM  customers

--DATEDIFF: CALCULAR LA DIFERENCIA EN DIAS ENTRE DOS FECHAS.
SELECT DATEDIFF(end_date, start_date) AS days_passed FROM products; 